package org.codewithmagret.rest.member;

import jakarta.persistence.*;
import org.codewithmagret.rest.tournament.Tournament;

import java.util.HashSet;
import java.util.Set;

/**
 * Represents a member entity in the system.
 * This class is mapped to a database table using JPA annotations.
 * Each member has a unique ID, name, address, email, membership type,
 * phone number, start date of membership, and duration of membership.
 * The ID is automatically generated by the database and serves as the
 * primary key for the member.
 * The name, address, email, membership type, phone number, start date of membership,
 * and duration of membership are all required fields that provide essential
 */
@Entity
public class Member {
    /**
     * The unique identifier for the member.
     * This field is automatically generated by the database and serves as the primary key for the member.
    */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the member
     * This field is required and represents the member's full name.
     */
    private String name;

    /**
     * The address of the member
     * This field is required and represents the member's address.
     */
    private String address;

    /**
     * The email of the member
     * This field is required and represents the member's email address.
     */
    private String email;

    /**
     * The member membership type
     * This field is required and represents the type of membership of the member
     */
    private String membershipType;

    /**
     * The member phone number
     * This field is required and represents the member's phone number
     */
    private String phoneNumber;

    /**
     * The member start date
     */
    private String membershipStartDate;

    /**
     * The member membership duration
     */
    private String membershipDuration;

    /**
     * Tournaments the member is participating in.
     * This is the inverse side of the many-to-many relationship.
     */
    @ManyToMany(mappedBy = "members")
    private Set<Tournament> tournaments =  new HashSet<>();

    /**
     * Default constructor required by JPA.
     * Initializes a new instance of the Member class.
     */
    public Member() {
    }

    /**
     * Gets the unique identifier of the member.
     * @return ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Gets the name of the member
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the member
     * @param name the name of the member
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the address of the member
     * @return address
     */
    public String getAddress() {
        return address;
    }

    /** Sets the address of the member
     * @param address the address of the member
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Gets the email of the member
     * @return email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email of the member
     * @param email of the member
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets membership type of the member
     * @return membershipType of the member
     */
    public String getMembershipType() {
        return membershipType;
    }

    /**
     * Sets membership type of the member
     * @param membershipType of the member
     */
    public void setMembershipType(String membershipType) {
        this.membershipType = membershipType;
    }

    /**
     * Gets phone number of the member
     * @return phoneNumber of the member
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets phone number of the member
     * @param phoneNumber of the member
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Gets Membership start date of the member
     * @return membershipStartDate of the member
     */
    public String getMembershipStartDate() {
        return membershipStartDate;
    }

    /**
     * Sets Membership start date of the member
     * @param membershipStartDate of the member
     */
    public void setMembershipStartDate(String membershipStartDate) {
        this.membershipStartDate = membershipStartDate;
    }

    /**
     * Gets Membership duration of the member
     * @return membershipDuration of the member
     */
    public String getMembershipDuration() {
        return membershipDuration;
    }

    /**
     * Sets Membership duration of the member
     * @param membershipDuration of the member
     */
    public void setMembershipDuration(String membershipDuration) {
        this.membershipDuration = membershipDuration;
    }

    /**
     * Gets the tournaments the member is participating in.
     *
     * @return set of tournaments
     */
    public Set<Tournament> getTournaments() {
        return tournaments;
    }

    /**
     * Sets the tournaments the member is participating in.
     *
     * @param tournaments set of tournaments
     */
    public void setTournaments(Set<Tournament> tournaments) {
        this.tournaments = tournaments;
    }

    /**
     * toString method which helps to print a readable format of the object
     * @return string representation of the object
     */
    @Override
    public String toString() {
        return "Member{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", email='" + email + '\'' +
                ", membershipType='" + membershipType + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", membershipStartDate='" + membershipStartDate + '\'' +
                ", membershipDuration='" + membershipDuration + '\'' +
                '}';
    }
}
